/**
 * `make status` — regenerate STATUS.md by ACTUALLY RUNNING the milestone smoke
 * checks (§14.2), so the checklist can't drift from reality. Each line is
 * checked only when its verify command passes, stamped with date + commit.
 */
import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

function ok(cmd: string, args: string[]): boolean {
  try {
    execFileSync(cmd, args, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

console.log('status: running smoke checks (this runs the real test/eval suite)…');
const typecheck = ok('node', ['scripts/typecheck.mjs']);
const eslint = ok('npx', ['eslint', '.']);
const boundary = ok('npx', ['depcruise', '--config', '.dependency-cruiser.cjs', 'packages']);
const test = ok('npx', ['vitest', 'run']);
const evalOk = ok('npx', ['tsx', 'packages/cli/src/eval.ts']);
const lint = eslint && boundary;

const commit = (() => {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch {
    return 'uncommitted';
  }
})();
const date = process.env.STATUS_DATE ?? new Date().toISOString().slice(0, 10);

interface Row {
  id: string;
  name: string;
  verify: string;
  pass: boolean;
}
const rows: Row[] = [
  { id: 'M0', name: 'Scaffold + CI', verify: 'make verify', pass: typecheck && lint && test },
  { id: 'M1', name: 'Contracts + fixtures', verify: 'make test', pass: test },
  { id: 'M2', name: 'Core linearizer', verify: 'make eval', pass: evalOk },
  { id: 'M3', name: 'Ingest (fixture + sem)', verify: 'make test', pass: test },
  { id: 'M4', name: 'Server API', verify: 'make test', pass: test },
  { id: 'M5', name: 'Web spine (render-tested) + eval report', verify: 'make test / make eval', pass: test && evalOk },
  { id: 'M6', name: 'Portability proven (boundary-clean)', verify: 'make lint', pass: boundary },
];

const lines = rows
  .map((r) => `| ${r.id} | ${r.pass ? '✅' : '⬜'} | ${r.name} | \`${r.verify}\` | ${date} | ${commit} |`)
  .join('\n');

const allGreen = rows.every((r) => r.pass);
const md = `# STATUS

_Generated by \`make status\` on ${date} (commit \`${commit}\`). Do not hand-edit — it
re-runs the smoke checks so it can't drift from reality (§14.2)._

Overall: ${allGreen ? '✅ all milestones green' : '⬜ some checks failing — see below'}

| # | done | milestone | verify | date | commit |
|---|------|-----------|--------|------|--------|
${lines}

## Raw check results
- typecheck: ${typecheck ? 'pass' : 'FAIL'}
- eslint: ${eslint ? 'pass' : 'FAIL'}
- boundary (dependency-cruiser, §11.6): ${boundary ? 'pass' : 'FAIL'}
- tests (vitest, §11): ${test ? 'pass' : 'FAIL'}
- eval (scorecard L1–L6 + determinism, §13.3): ${evalOk ? 'pass' : 'FAIL'}

M6 ships the portability PROOF: the boundary check above mechanically guarantees
\`core\`, \`contracts\`, and the shared \`Spine\` carry no platform-specific imports,
and the eval report renders that same \`Spine\` from a plan alone.

## Deferred (not verified by this report)
- **Browser-driven Playwright e2e (§11.7):** deferred. The spine is verified via
  static-markup + jsdom render tests under \`make test\` (no real browser is driven).
- **VS Code webview (§9):** not built. Portability is proven by the boundary
  check (M6), not by an actual webview host.
`;

writeFileSync('STATUS.md', md);
console.log(`status: wrote STATUS.md (${allGreen ? 'all green' : 'some failing'}).`);
if (!allGreen) process.exit(1);
